version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpa-campaigns-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - cpa-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: cpa-campaigns-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cpa-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: cpa-campaigns-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cpa_campaigns
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: cpa_user
      MYSQL_PASSWORD: cpa_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - cpa-network

  redis:
    image: redis:7-alpine
    container_name: cpa-campaigns-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cpa-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cpa-campaigns-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8081:80"
    networks:
      - cpa-network
    depends_on:
      - db

volumes:
  db_data:
  redis_data:

networks:
  cpa-network:
    driver: bridge
